version: "3"
services:
  database:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - "./influxdb-volume:/var/lib/influxdb"
  dashboard:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "./grafana-volume:/var/lib/grafana"
